### ISSUE TITLE
S3 protocol bucket path

### ISSUE THREAD

**Issue by ianmh** [sst/open-next#151]
Basically it needs to do an additional check of the url to see if there's an s3 protocol, then use that raw path.

**Comment by khuezy** [comment]
NOTE: NextjsSite needs to override https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/SsrSite.ts#L449 and add the image optimization function in order for users to attach the correct perms to their external bucket.

**Comment by khuezy** [comment]
https://discord.com/channels/983865673656705025/1124167941664026725

Looks to be bad project configuration. I'm not sure if this feature request is warranted since you can put a different bucket behind CF and use that URL as your `src`. But if there are use cases to pass in a different S3 bucket, then we can bump up priority.

**Comment by conico974** [comment]
You can now override the default image loader in V3
