### ISSUE TITLE
Create `S3Client` and `DynamoDBClient` in `cache.ts`

### ISSUE THREAD

**Issue by fwang** [sst/open-next#265]
Currently `S3Client` and `DynamoDBClient` are created in `server-adapter.ts` and passed into `cache.ts` via `globalThis`.
https://github.com/sst/open-next/blob/1ce30f6289b43d803aefa51b6a860c8af1b9e65e/packages/open-next/src/adapters/server-adapter.ts#L38-L45

Any benefit over creating them directly in `cache.ts`?

**Comment by conico974** [comment]
Yes, i think it was this that was causing an issue when the lambda was up for a very long time and with enough request, the lambda was crashing with `EMFILE too many open files`.

The problem is that the incremental cache is recreated on every request and required on every request (And the require cache is also cleared). It was causing some file to stay open which after enough time would cause the issue. It was also making the memory grow out of control

Unfortunately i haven't been able to successfully reproduce this issue since it requires enough traffic to a single lambda instance

**Comment by fwang** [comment]
Documented above explanation in the comment.
https://github.com/sst/open-next/blob/746d73a8eb8b0e9e0c5d1101c441ec22315dd093/packages/open-next/src/adapters/server-adapter.ts#L38-L43
