### ISSUE TITLE
publishing to v3 tag for use with sst ion

### ISSUE THREAD

**Issue by aryasaatvik** [sst/open-next#478]
How do we feel about specifying `--tag v3` to the changeset set publish command and then using v3 tag instead of a pinned version in sst ion https://github.com/sst/ion/blob/dev/platform/src/components/aws/nextjs.ts#L29. 

This is not a blocker for me since I can specify a custom build command in sst.config and open-next.config. But assuming we follow semantic versioning, it would be nice to automatically get new features and bug fixes for open-next in sst ion projects.

If we do decide to take this approach we should also consider renaming the default branch to v3

**Comment by conico974** [comment]
Not a big fan of this approach at all.
If we do that it could break some deployment without any changes. We could introduce some regression in a new release that would break your deployment even if you've made no change at all to your next website (you change something else in the stack, which will trigger an update of the website since it's not using the same version of OpenNext )

It could even break prod environment even if you've tested everything in a staging env before (You test everything in staging, we make a release while you run test in staging, you deploy in prod, boom it crashes in prod)

The thing that we could probably do is create PR in ion and sst v2 to update the version of OpenNext used there every time we make a release.

**Comment by aryasaatvik** [comment]
makes sense. I bumped the default version in sst ion https://github.com/sst/ion/pull/752
