### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by fredtcaroli** [sst/open-next#511]
In the [migration page](https://open-next.js.org/migration), under **Vercel**, you can read:

> Streaming by default is disabled in open-next (for now). It is very experimental right now see [here](https://open-next.js.org/inner_workings/streaming) for more info.

That link on "here" is broken.

**Comment by khuezy** [comment]
Thanks for the report, pushed to main since it was a small doc change: https://github.com/sst/open-next/commit/faefb33a2a485c571c2cc43680f1b702a03b58c7

**Comment by khuezy** [comment]
Should be fixed now, thanks!

**Comment by fredtcaroli** [comment]
Is streaming still experimental in v3? Now the link is pointing to a doc page from v2

**Comment by khuezy** [comment]
Hard to say really, since AWS themselves are still working/tweaking their streaming implementation. If you try it on your AWS account and it works, then it should be "stable" for you* - the disclaimer being AWS can also break streaming when they do an upgrade to the runtime and it breaks... which they've done 2 times iirc.

**Comment by khuezy** [comment]
Cloudflare workers supports streaming, I'm not 100% sure how stable it is. You may hear about Cloudflare support in the near future.
