### ISSUE TITLE
Support Streaming

### ISSUE THREAD

**Issue by fwang** [sst/open-next#79]
AWS Lambda just introduced streaming capabilities via Lambda URLs. Opening this issue to gather some thoughts/interests from the community.

Ref:
https://beta.nextjs.org/docs/data-fetching/streaming-and-suspense
https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/

**Comment by khuezy** [comment]
@conico974 were you able to cache the streamed data? I tried playing w/ streaming in server-adapter but the content type ended up being an `octet-stream`

**Comment by conico974** [comment]
Yes it was kind of working, i hacked something here : https://github.com/conico974/open-next/blob/688150d0a09d78a12f0ba926097c8282b6ec2745/packages/open-next/src/adapters/response.ts#L85 to set the content type.
This was the only way i found to set the headers on the response stream, but i haven't looked too much into this.

There is also a `setContentType` method on the `responseStream` object but we need to call this before writing anything to the stream, otherwise it will log an error and set the content type to `octet-stream`

**Comment by DavidHooper** [comment]
@conico974 I've forked your commit and investigating further. Found this function sets content type after the stream has already been written to.
https://gist.github.com/magJ/63bac8198469b6a25d5697ad490d31e6#file-index-mjs-L806

**Comment by conico974** [comment]
@DavidHooper Nice catch looking at the runtime.
This function is actually called from user code, so it's likely something i have done or that you've done.
Looking at the gist, the response stream provided to us is actually https://gist.github.com/magJ/63bac8198469b6a25d5697ad490d31e6#file-index-mjs-L197.
We should probably rewrite the response class from open-next around that class

**Comment by passgoco** [comment]
Is there any update on this? I would love to see it implemented!

**Comment by khuezy** [comment]
@passgoco https://discord.com/channels/983865673656705025/1027265626085019769/1149742408565800990
Still experimental, chunks aren't compressed, we're looking into rewriting the http server. Help us if you can.
